version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: appname
    container_name: appname
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - '3000:3000'
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    working_dir: /home/node/app
    command: yarn prod
    # depends_on:
    #   - db

  # db:
  #   image: postgres
  #   restart: always
  #   container_name: planny-postgres
  #   environment:
  #     POSTGRES_PASSWORD: asdf1234
  #     POSTGRES_USER: user
  #     POSTGRES_DB: db
  #   ports:
  #     - '5432:5432'
  #   volumes:
  #     - db-data:/var/lib/postgresql/data/

volumes:
  node_modules:
  db-data:
